### ISSUE TITLE
Packaging environment

### ISSUE THREAD

**Issue by szepeviktor** [gplessis/dotdeb-php5#68]
Could you document your packaging environments?

**Comment by gplessis** [comment]
Basically, I boot up an up-to-date stock Debian box using the target distribution (Wheezy, Squeeze, ...), install the build dependencies from the package I want to build, and just build it. If you're familiar with Docker, here is the Dockerfile describing this :

```
FROM debian:wheezy
MAINTAINER Guillaume Plessis "gui@go-text.me"

ENV DEBIAN_FRONTEND noninteractive

RUN echo "deb http://http.debian.net/debian/ wheezy main contrib non-free" > /etc/apt/sources.list
RUN echo "deb http://http.debian.net/debian/ wheezy-updates main contrib non-free" >> /etc/apt/sources.list
RUN echo "deb http://http.debian.net/debian/ wheezy-backports main contrib non-free" >> /etc/apt/sources.list
RUN echo "deb http://security.debian.org/ wheezy/updates main contrib non-free" >> /etc/apt/sources.list

RUN echo "APT::Install-Recommends "false";" > /etc/apt/apt.conf.d/10recommends
RUN echo "APT::Install-Suggests "false";" >> /etc/apt/apt.conf.d/10recommends

RUN apt-get update
RUN apt-get dist-upgrade -y

RUN apt-get install -y build-essential devscripts equivs libwww-perl

ADD debian/control /root/
RUN mk-build-deps --install --tool 'apt-get -y' --remove /root/control && rm -f /root/control

ADD . /usr/src/builddir
WORKDIR /usr/src/builddir

RUN rm -f Dockerfile
RUN uscan --download-current-version
RUN dpkg-buildpackage

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/src/builddir
```

I try to follow the [git-buildpackage flow](http://honk.sigxcpu.org/projects/git-buildpackage/manual-html/gbp.html) now, having an `upstream*` branch/es, as well as a `pristine-tar` one, along with `master*`work branches, named after the upstream branch and target disturb versions. My Github repos are progressively being converted to this.

Using Docker, Jenkins and Aptly might be the next step for me to automatize the building/testing/publishing of packages.

Please tell me if you need more info.

**Comment by szepeviktor** [comment]
Thank you!
It is good to hear that you plan to automate builds.
