### ISSUE TITLE
FPM with version 5.5.20 not working/crashing

### ISSUE THREAD

**Issue by iquito** [gplessis/dotdeb-php5#69]
PHP-FPM with version 5.5.20 does not work on any of my servers - I installed it on 4 different servers (via aptitude upgrade from version 5.5.19), and always the same thing happens:

- The first request to a page works as usual
- Every subsequent request leads to immediate "502 Bad Gateway" error message (using Nginx 1.7.8)
- PHP-FPM seems to still run (is still listed in top), but does not work anymore. No log entries, except for Nginx errors in the log like this for all PHP requests: "2014/12/21 16:06:46 [error] 2619#0: *101 recv() failed (104: Connection reset by peer) while reading response header from upstream"
- Disabling plugins or opcache does not change this problem, yet if opcache is disabled, the first two requests work, not only the very first request for a page

This problem is reproducible on all my servers with 5.5.20 just by loading phpmyadmin - first request works, every following request fails. CLI is not affected and works fine. I reversed to 5.5.19 by downloading and manually installing the deb-packages from archives.dotdeb.org

If any more information is needed, I would gladly provide it - currently, I deactivated FPM on three of servers which have 5.5.20 installed and am hoping for a fix for this issue.

**Comment by gplessis** [comment]
I'm trying to reproduce the problem on my side. Could you please tell me what's the version on libxml2 on your system? Thanks.

**Comment by iquito** [comment]
It's version 2.8.0+dfsg1-7+wheezy2 - all software is up-to-date as of the 21st of December, when I did a complete aptitude upgrade.

For version 5.6.4 somebody also commented that FPM is not working anymore: https://www.dotdeb.org/2014/12/20/php-5-6-4-for-wheezy/#comment-34378

**Comment by antoine64** [comment]
> For version 5.6.4 somebody also commented that FPM is not working anymore: https://www.dotdeb.org/2014/12/20/php-5-6-4-for-wheezy/#comment-34378

It's me.

I'm using PHP 5.6.4 on Debian Wheezy amd64.
All is up to date.

/etc/apt/sources.list
```
deb http://packages.dotdeb.org wheezy all
deb-src http://packages.dotdeb.org wheezy all

deb http://packages.dotdeb.org wheezy-php56 all
deb-src http://packages.dotdeb.org wheezy-php56 all

deb http://ftp.fr.debian.org/debian wheezy main contrib non-free
deb-src http://ftp.fr.debian.org/debian wheezy main contrib non-free

deb http://ftp.fr.debian.org/debian testing main contrib non-free
deb-src http://ftp.fr.debian.org/debian testing main contrib non-free

deb http://security.debian.org wheezy/updates main contrib non-free
deb-src http://security.debian.org wheezy/updates main contrib non-free

deb http://security.debian.org testing/updates main contrib non-free
deb-src http://security.debian.org testing/updates main contrib non-free

deb http://ftp.fr.debian.org/debian wheezy-updates main contrib non-free
deb-src http://ftp.fr.debian.org/debian wheezy-updates main contrib non-free

deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/debian wheezy main
deb-src http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/debian wheezy main
```

/etc/apt/preferences
```
Package: *
Pin: release o=apt-build
Pin-Priority: 995

Package: *php*
Pin: release o=packages.dotdeb.org
Pin-Priority: 995

Package: *
Pin: release o=Debian,a=stable-updates,l=Debian
Pin-Priority: 990

Package: *
Pin: release o=Debian,a=stable,l=Debian-Security
Pin-Priority: 990

Package: *
Pin: release o=Debian,a=stable,l=Debian
Pin-Priority: 990

Package: *
Pin: release o=packages.dotdeb.org
Pin-Priority: 100

Package: *
Pin: release o=Debian,a=testing,l=Debian-Security
Pin-Priority: 90

Package: *
Pin: release o=Debian,a=testing,l=Debian
Pin-Priority: 90
```

dpkg -l 'php*' | grep '^.i'
```
ii  php-gettext                           1.0.11-1                           all          read gettext MO files directly, without requiring anything other than PHP
ii  php-pear                              5.6.4-1~dotdeb.1                   all          PEAR - PHP Extension and Application Repository
ii  php-tcpdf                             6.0.093+dfsg-1                     all          PHP class for generating PDF files on-the-fly
ii  php5                                  5.6.4-1~dotdeb.1                   all          server-side, HTML-embedded scripting language (metapackage)
ii  php5-cli                              5.6.4-1~dotdeb.1                   amd64        command-line interpreter for the php5 scripting language
ii  php5-common                           5.6.4-1~dotdeb.1                   amd64        Common files for packages built from the php5 source
ii  php5-curl                             5.6.4-1~dotdeb.1                   amd64        CURL module for php5
ii  php5-fpm                              5.6.4-1~dotdeb.1                   amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php5-gd                               5.6.4-1~dotdeb.1                   amd64        GD module for php5
ii  php5-imagick                          1:3.1.2-1~dotdeb.1                 amd64        Provides a wrapper to the ImageMagick library
ii  php5-imap                             5.6.4-1~dotdeb.1                   amd64        IMAP module for php5
ii  php5-intl                             5.6.4-1~dotdeb.1                   amd64        internationalisation module for php5
ii  php5-mcrypt                           5.6.4-1~dotdeb.1                   amd64        MCrypt module for php5
ii  php5-memcache                         1:3.0.8-1~dotdeb.1                 amd64        memcached extension
ii  php5-memcached                        1:2.2.0-1~dotdeb.1                 amd64        PHP extension for interfacing with memcached via libmemcached library
ii  php5-mysqlnd                          5.6.4-1~dotdeb.1                   amd64        MySQL module for php5 (Native Driver)
ii  php5-pspell                           5.6.4-1~dotdeb.1                   amd64        pspell module for php5
ii  php5-recode                           5.6.4-1~dotdeb.1                   amd64        recode module for php5
ii  php5-snmp                             5.6.4-1~dotdeb.1                   amd64        SNMP module for php5
ii  php5-sqlite                           5.6.4-1~dotdeb.1                   amd64        SQLite module for php5
ii  php5-tidy                             5.6.4-1~dotdeb.1                   amd64        tidy module for php5
ii  php5-xmlrpc                           5.6.4-1~dotdeb.1                   amd64        XML-RPC module for php5
ii  php5-xsl                              5.6.4-1~dotdeb.1                   amd64        XSL module for php5
ii  phpmyadmin                            4:4.2.8-1                          all          MySQL web administration tool
```

**Comment by gplessis** [comment]
@antoine64 : could you please be more precise on "is not working anymore"? Is php5-fpm launching and working only for a few requests, as @iquito described. Or is it not launching at all?

**Comment by antoine64** [comment]
It's working but since the upgrade, new .sock are not created in /var/lib/php5-fpm. So I have this kind of errors for new websites I create : 
`2015/01/04 19:27:05 [crit] 30653#0: *137963 connect() to unix:/var/lib/php5-fpm/web15.sock failed (2: No such file or directory) while connecting to upstream, client: 109.214.13.221, server: ***.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web15.sock:", host: "www.***.fr"`

I tried /etc/init.d/php5-fpm restart but no response is returned.

**Comment by gplessis** [comment]
@antoine64 which version did you upgrade from?

Could you please :
* check your `/var/lib/php5-fpm` directory permissions?
* check your pool configuration and make sure :
 * that the `listen.user` and `listen.group` are `www-data`, so that Nginx can read the socket
 * that the `user`and `group` defined here can write to the `/var/lib/php5-fpm/` directory
* check that using `/var/lib/php5-fpm` is legit and on purpose. Usually, `/var/run/` is used for php5-fpm.

For example, here is a usual pool config :
```
listen = /var/run/php5-fpm.sock
listen.owner = www-data
listen.group = www-data
user = www-data
group = www-data
```

**Comment by antoine64** [comment]
It's OK. I just killed all php-fpm instances and it creates the .sock. Problem solved ;)

**Comment by gplessis** [comment]
@iquito : let's focus on your issue. Are you using the `listen.allowed_clients` in your pool config or is it left to its default value?

**Comment by iquito** [comment]
The easierst is probably if I just post the FPM pool config file without the comments:

[www]

listen = 192.168.10.203:9000
listen.allowed_clients = 127.0.0.1,192.168.10.203,192.168.10.208,192.168.10.100,192.168.10.105,192.168.10.103,192.168.10.108
user = www-data
group = www-data
pm = dynamic
pm.max_children = 3000
pm.start_servers = 50
pm.min_spare_servers = 10
pm.max_spare_servers = 200
pm.status_path = /fpmess0190
request_slowlog_timeout = 1m
slowlog = /var/log/php.slow.$pool.log
chdir = /

Nothing really special, very few config files have additional variables, except for the bare minimum. You could not yet reproduce my issue?

**Comment by gplessis** [comment]
@iquito : then you might be bitten by [this bug](https://bugs.php.net/bug.php?id=68751). Could you temporarily test by allowing all clients on the FPM side and firewall your port 9000 instead?

**Comment by iquito** [comment]
I just limited the listen.allowed_clients to one IP address per pool, as the bug indicates the first IP address listed would work, just the following IPs would not. When I first restartet PHP-FPM on an affected server, it seemed as though requests to 192.168.10.208 worked when called from 192.168.10.208, but not from another IP address. Yet when I restartet it again, it now generally seems to work - as far as I can tell. I switched it to production, and everything is okay so far, it has been working for 20 minutes now.

Yet my problem still seems different to the bug you linked to - in my case, connections to FPM aren't refused according to nginx, they are just terminated (connection reset by peer). Also, if multiple addresses are listed for only one pool, then all pools refuse to work - even the ones with only one IP address in listen.allowed_clients . My case seems to "crash" PHP-FPM in some way. If the pools with one IP address would have worked, I would have noticed, because I have pools for local tasks and test sites where only 127.0.0.1 can connect.

Should I post a new bug report on bugs.php.net, or comment on the existing bug report? What would you recommend? If it's a bug in PHP I am surprised almost nobody noticed this bug so far, restricting PHP-FPM to multiple IP addresses would seem like a common configuration choice.

**Comment by gplessis** [comment]
@iquito : Yes, you should comment on the existing bug report, with your Nginx and FPM pool configs, the symptoms, and ask if the fix is relevant.

**Comment by iquito** [comment]
Ok, I added a comment about my problem and also linked here for a detailed reference. Thanks for your help! Hopefully the PHP team releases a new version soon.

**Comment by gplessis** [comment]
@iquito : I'll try to provide (patched 5.5.20 / 5.5.21 if available) packages in the next few days, so that we can provide feedback to the PHP dev team.

**Comment by iquito** [comment]
Thanks, that would be great.

**Comment by gplessis** [comment]
@iquito could you please try with [this package](https://www.dotdeb.org/php5-fpm_5.5.20-1~dotdeb.1_amd64.deb) and give me a feedback?

**Comment by iquito** [comment]
I installed the package, and it seems to work - no problems with FPM anymore, and no other errors.

**Comment by iquito** [comment]
PHP 5.5.21 was just released with the fix to FPM, so I will close this issue.
