### ISSUE TITLE
Please make squeeze-php53-nosuhosin tree

### ISSUE THREAD

**Issue by Profforgr** [gplessis/dotdeb-php5#73]
Hi.

Suhosin patch cause problems in most workloads. It really should be optional via additional package (php5-suhosin). At the moment on squeeze-php53 tree no way to disable suhosin. I've tried all known methods, but it does not work.

Can you please be so kind to make squeeze-php53-nosuhosin tree with removed suhosin and push it to repository?

Sincerely,

Alex.

**Comment by gplessis** [comment]
Because PHP 5.3 has reached its end of life last summer, no additional changes will be brought to these packages. You really should upgrade to PHP 5.4+ to kill two birds (security update + no suhosin) with one stone.

**Comment by Profforgr** [comment]
> Because PHP 5.3 has reached its end of life last summer, no additional changes will be brought to these packages. You really should upgrade to PHP 5.4+ to kill two birds (security update + no suhosin) with one stone.

I really understand that. I am using PHP 5.5 in most workloads and will use newer versions when available. But old CMS engines (in this case, Bitrix) do no work with php 5.4 and upper correctly. Unfortunately there are no way to fix that. Suhosin patch in my case prevents .htacess php variables change, which makes it impossible to set separate settings for websites.

If it's possible, it would be perfect if you can make this tree. It should be very easy for you and it's one-time operation as no new updates will be pushed to php 5.3..


Sincerely,

Alex.
