### ISSUE TITLE
Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by TheTotenkopf** [gplessis/dotdeb-php5#75]
Hello,

im aways getting this error when I'm trying to install php5-fpm.

"Sub-process /usr/bin/dpkg returned an error code (1)"

Im Using Debian 7 wheezy only this package make problems to install.

**Comment by gplessis** [comment]
There's no way for me to diagnose your issue without the exact error message. Could you please find it in the standard (error) output on your terminal or in your logs?

**Comment by TheTotenkopf** [comment]
Heres the terminal with the error:
http://screencloud.net/v/wbHo

here the log (php5-fpm.log)

http://screencloud.net/v/9IKf

and the dpkg.log

http://screencloud.net/v/3zbj

**Comment by gplessis** [comment]
It's strange that you don't have any pool defined. Please try to put this minimal pool in `/etc/php5/fpm/pool.d/www.conf` and restart the installation/upgrade :
```
[www]
user = www-data
group = www-data
listen = /var/run/php5-fpm.sock
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
chdir = /
```

**Comment by TheTotenkopf** [comment]
Worked thanks for the help
