### ISSUE TITLE
php5-mongo 1.6.x versions are unstable. Use 1.5.8 

### ISSUE THREAD

**Issue by niels-nijens** [gplessis/dotdeb-php5#78]
All the 1.6.x versions of the php5-mongo packages have been unstable thus far (not your fault, I know).

My suggestion is that you include version 1.5.8 with new PHP5.4+ builds until the package maintainers sort things out. 

PS. Thanks for this great service!

**Comment by gplessis** [comment]
Do the latest 1.6 version solve your problem? If not, feel free to provide more details about it.

**Comment by niels-nijens** [comment]
Yes, the 1.6.4 version of the extension seems to have fixed all the issues. Thanks.
