### ISSUE TITLE
php5-apc can't work

### ISSUE THREAD

**Issue by hqin2013** [gplessis/dotdeb-php5#80]
Hi,

I just use apt-get install php5-apc,but found it doesn't work in Debian 6.

It reports: E: Unable to locate package php5-apc

added in source.list
deb http://packages.dotdeb.org squeeze all
deb-src http://packages.dotdeb.org squeeze all

Regards
hqin

**Comment by gplessis** [comment]
php5-apc is available : http://packages.dotdeb.org/dists/squeeze/php5-pecl/binary-amd64/

Could you please provide [some more information](https://www.dotdeb.org/2012/08/24/how-to-post-useful-bug-reports/) and make sure that you did run `apt-get update` before trying to install php5-apc.

**Comment by hqin2013** [comment]
What is your distribution? Debian6 
What is your architecture? i386
Which exact PHP version are you using? 5.3.39
Which SAPI are you using? FPM
What’s the full content of your /etc/apt/sources.list and /etc/apt/sources.list.d files?
deb http://ftp.us.debian.org/debian/ squeeze main
deb-src http://ftp.us.debian.org/debian/ squeeze main
deb http://security.debian.org/ squeeze/updates main
deb-src http://security.debian.org/ squeeze/updates main
deb http://packages.dotdeb.org squeeze all
deb-src http://packages.dotdeb.org squeeze all

What is the result of dpkg -l 'php*' | grep '^.i' ?it's a lot ,except php-apc
Please provide a textual description of the bug.  apt-get install php5-apc,get error:E: Unable to locate package php5-apc
Please provide any modified configuration directive. no 
Please provide a backtrace, after installing php5-dbg.:i used https://github.com/Xeoncross/lowendscript , everything is ok in last week.

**Comment by gplessis** [comment]
> What is the result of dpkg -l 'php*' | grep '^.i' ?
>> it's a lot ,except php-apc

Please paste it here, this may be the source of the problem : a mix of PHP-related packages and extensions coming from both Debian and Dotdeb.

**Comment by hqin2013** [comment]
I tried again & again.... found:
wget -q -O - http://www.dotdeb.org/dotdeb.gpg | apt-key add -

just execute this first,then everything is ok
