### ISSUE TITLE
package php5-apcu for debian is broken

### ISSUE THREAD

**Issue by teo1978** [gplessis/dotdeb-php5#81]
See this (I erroneously reported it on Debian):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782618

**Comment by gplessis** [comment]
Ok. Could you please provide some more information on your setup? https://www.dotdeb.org/2012/08/24/how-to-post-useful-bug-reports/

**Comment by Seraf** [comment]
Hello @gplessis ,

I have a problem with apcu using the last version 5.5.26 : 
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/apcu.so' - /usr/lib/php5/20121212/apcu.so: undefined symbol: pcre_exec in Unknown on line 0

I use : 
ii  php5-apcu                          5.5.26-1~dotdeb+7.3           amd64        apcu module for php5

Thanks

**Comment by gplessis** [comment]
@Seraf ok. Which SAPI (CLI, CGI, FPM, Apache...) are you using?

**Comment by MaZderMind** [comment]
Copying extra Info from #85:

apcu does not load on cli anymore, becuause of undefined symbol: pcre_exec:
````
php -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/apcu.so' - /usr/lib/php5/20121212/apcu.so: undefined symbol: pcre_exec in Unknown on line 0
````

But as apcu does nothing useful on cli anyway, it's easy to disable it:
````
php5dismod -s cli apcu
````

Works in Apache nicely, though.

**Comment by Seraf** [comment]
@gplessis Sorry, yes as @MaZderMind said, I have the problem on cli actually (didn't try with fpm as my need is only on cli by now).

**Comment by mattGNU** [comment]
Some problem here : 
 $~  php -m                                                                                                                                                                             
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/apcu.so' - /usr/lib/php5/20121212/apcu.so: undefined symbol: pcre_exec in Unknown on line 0

and in my Symfony apps : 
Symfony\Component\Debug\Exception\UndefinedFunctionException # 0 - Attempted to call function "apc_fetch" from namespace "Doctrine\Common\Cache".

**Comment by centur73** [comment]
Ich have the same problem:

- OS: Debian wheezy, amd64
- PHP-Version: 5.5.26
- SAPI: mod_php
- dpkg -l php* | grep ii 

ii  php5                               5.5.26-1~dotdeb+7.3           all          server-side, HTML-embedded scripting language (metapackage)
ii  php5-apcu                          5.5.26-1~dotdeb+7.3           amd64        apcu module for php5
ii  php5-cgi                           5.5.26-1~dotdeb+7.3           amd64        server-side, HTML-embedded scripting language (CGI binary)
ii  php5-cli                           5.5.26-1~dotdeb+7.3           amd64        command-line interpreter for the php5 scripting language
ii  php5-common                        5.5.26-1~dotdeb+7.3           amd64        Common files for packages built from the php5 source
ii  php5-curl                          5.5.26-1~dotdeb+7.3           amd64        CURL module for php5
ii  php5-gd                            5.5.26-1~dotdeb+7.3           amd64        GD module for php5
ii  php5-intl                          5.5.26-1~dotdeb+7.3           amd64        internationalisation module for php5
ii  php5-mysql                         5.5.26-1~dotdeb+7.3           amd64        MySQL module for php5
ii  php5-readline                      5.5.26-1~dotdeb+7.3           amd64        Readline module for php5
ii  php5-sqlite                        5.5.26-1~dotdeb+7.3           amd64        SQLite module for php5
ii  php5-tidy                          5.5.26-1~dotdeb+7.3           amd64        tidy module for php5
ii  php5-xdebug                        5.5.26-1~dotdeb+7.3           amd64        xdebug module for php5
ii  php5-xmlrpc                        5.5.26-1~dotdeb+7.3           amd64        XML-RPC module for php5
ii  php5-xsl                           5.5.26-1~dotdeb+7.3           amd64        XSL module for php5

**Comment by gplessis** [comment]
Ok, I'll work on a fix today. If you need to downgrade to PHP 5.5.25, packages are still present in the repo, you just have to set the version explicitly in your apt-get :
```
apt-get install php5-fpm=5.5.25-1~dotdeb+7.1 0 php5-common=5.5.25-1~dotdeb+7.1 ....
```

**Comment by gplessis** [comment]
Guys, could you please do me a favor and install/replace your faulty SAPIs (CGI, FPM, CLI) with the corresponding packages from http://ci.dotdeb.org/job/dotdeb-php5/branch/master-5.5%2Fwheezy/10/artifact/jenkins-dotdeb-php5-master-5.5-wheezy-10/src/ and tell me if they fix the problem.

If so, I'll post updated packages on the public repo.

**Comment by szaqal83** [comment]
Works for me.

**Comment by Seraf** [comment]
Hello,

It works for me too : 

root@localhost:~# php -v
PHP 5.5.26-1~dotdeb+7.3 (cli) (built: Jun 17 2015 21:34:52) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
root@localhost:~# php -m | grep apc
apc
apcu

:+1:  Thanks !

**Comment by gregorg** [comment]
Hello, 

works for me too with 5.5.26-1~dotdeb+7.3

Thanks ! :+1:

**Comment by centur73** [comment]
Works for me.

**Comment by miklos-martin** [comment]
:+1:

**Comment by mattGNU** [comment]
:+1: Thanks

**Comment by MyWay** [comment]
Yes, it's working, thank you.

**Comment by laurent35240** [comment]
Works for me

**Comment by gplessis** [comment]
Wow, thanks for your help :) I'll publish updated packages today.

**Comment by miklos-martin** [comment]
thank you

**Comment by gplessis** [comment]
PHP 5.5 packages have been updated
