### ISSUE TITLE
Jessie is missing from instructions

### ISSUE THREAD

**Issue by szepeviktor** [gplessis/dotdeb-php5#84]
Please update https://www.dotdeb.org/instructions/

**Comment by szepeviktor** [comment]
Consider taking down the `Log in` link from your WP site.
Some hard home-made security for you:
https://github.com/szepeviktor/wordpress-plugin-construction/tree/master/wordpress-fail2ban/block-bad-requests
https://github.com/szepeviktor/wordpress-plugin-construction/tree/master/wordpress-fail2ban/mu-plugin

**Comment by szepeviktor** [comment]
I am waiting for PHP-NG - even before it get stable.

**Comment by gplessis** [comment]
Fixed. Thanks.
